### ISSUE TITLE
Create git hook directory if it does not exist.

### ISSUE THREAD

**Issue by shiraji** [STAR-ZERO/gradle-githook#4]
Hi, Thanks for great plugin. 

Do you think it's good idea that if there is no hook directory, create that directory?

---

Implementation plan:

1. This plugin provides an option calls `createHooksDirIfNotExist` which the default value is false.
1. If the option set to true and there is no hook dirs, then create hook directory just before this line https://github.com/STAR-ZERO/gradle-githook/blob/master/githook/src/main/kotlin/com/star_zero/gradle/githook/GithookPlugin.kt#L15

**Comment by STAR-ZERO** [comment]
Looks nice 👍
Could you please make PR?
