### ISSUE TITLE
Wrong classpath for plugin in Docs

### ISSUE THREAD

**Issue by piacenti** [STAR-ZERO/gradle-githook#6]
Docs have `gradle.plugin.com.star-zero.gradle:githook:1.2.1` but gradle plugin repo actually has `com.star-zero.gradle:githook:1.2.1`

**Comment by STAR-ZERO** [comment]
Fixed https://github.com/STAR-ZERO/gradle-githook/commit/2d18b1de4db6059cc8396757e2d9404cf24d4ec1

Thanks 👍
